In [5]:
import numpy as np
ls = [1, 3, 6, 8, 89, 30]
a = np.array(ls)
a.shape = 2,3
print(a,type(a))
# Space Seperated and ndarray data type


[[ 1  3  6]
 [ 8 89 30]] <class 'numpy.ndarray'>


In [13]:
import numpy as np
ls = [ 3, 6, 8, 89, 130]
a = np.array(ls,dtype='int8')
print(a)

[   3    6    8   89 -126]


In [9]:
import numpy
ls = [1,2,3,4,5,6,7,8]
a = numpy.array(ls)
print(a)

[1 2 3 4 5 6 7 8]


In [19]:
import numpy as np
ls1 = ([[2,5,7],[6,8,9]])
ls2 = ([[3,5,7],[4,7,0]])
arr1 = np.array(ls1)
arr2 = np.array(ls2)
print(arr1)
arr2.shape = 3,2
print(arr2)
arr_re = np.dot(arr1,arr2) # With array we can easily perform Matrix Operation's (or np.divide(arr1,arr2) or np.multiply(arr1,arr2) or arr1*arr2)
print(arr_re)


[[2 5 7]
 [6 8 9]]
[[3 5]
 [7 4]
 [7 0]]
[[ 90  30]
 [137  62]]


In [17]:
ls1 = ([[2,5,7],[6,8,9]])
ls2 = ([[3,5,7],[4,7,0]])
for i in ls1:
    print(i)
print()
for i in ls2:
    print(i)
print()
r1 = len(ls1)
c1 = len(ls1[0])
r2 = len(ls2)
c2 = len(ls2[0])
res_ls = []
if (r1,c1 == r2,c2):
    for i in range (r1):
        tmp = []
        for j in range (c1):
            tmp.append(ls1[i][j]+ls2[i][j])
        res_ls.append(tmp) 
else :
    print('dimensions not valid')
for i in res_ls :
    print(i)



[2, 5, 7]
[6, 8, 9]

[3, 5, 7]
[4, 7, 0]

[5, 10, 14]
[10, 15, 9]


In [ ]:
ls1 = ([[2,5,7],[6,8,9]])
ls2 = ([[3,5,7],[4,7,0]])
for i in ls1:
    print(i)
print()
for i in ls2:
    print(i)
print()
r1 = len(ls1)
c1 = len(ls1[0])
r2 = len(ls2)
c2 = len(ls2[0])
res_ls = []
if (c1 == r2):
    for i in range (r1):
        tmp = []
        sum = 0
        for j in range (c1):
            for k in range (c2):
                sum += ls1[i][j]*ls2[j][k]
        res_ls.append(tmp) 
else :
    print('dimensions not valid')
for i in res_ls :
    print(i)



In [14]:
import numpy as np
n = input().split()
n.reverse()
arr = np.array(n,float)
print(arr)

[6. 5. 4. 3. 2.]


In [2]:
import numpy as np
ls = []
n = input().split()
count = (len(n)//3)
for i in range (0,len(n),count):
    ls1 = n[i:i+count]
    ls.append(ls1)
arr = np.array(ls,int)
arr.shape
print(arr)

ValueError: cannot reshape array of size 0 into shape (3,3)

In [1]:
import numpy as np
n = input().split()
r = int(n[0])
c = int(n[-1])
out = np.eye(r,c) # Identitcal Matrix eye method
print(out)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
import numpy as np
r,c = map(eval,input().split())
ls1 = list(map(eval,input().split()))
ls2 = list(map(eval,input().split()))
a = np.array(ls1)
b = np.array(ls2)
arr = a+b
arr.shape = 1,4
print(arr)
arr = a-b
arr.shape = 1,4
print(arr)
arr = a*b
arr.shape = 1,4
print(arr)
arr = a//b
arr.shape = 1,4
print(arr)
arr = a%b
arr.shape = 1,4
print(arr)
arr = a**b
arr.shape = 1,4
print(arr)

[[2 4 6 8]]
[[0 0 0 0]]
[[ 1  4  9 16]]
[[1 1 1 1]]
[[0 0 0 0]]
[[  1   4  27 256]]


In [5]:
import numpy as np
r,c = map(eval,input().split())
ls = []
for i in range (0,r):
    ls.append(list(map(eval,input().split())))
arr = np.array(ls)
arr.shape = r,c
t = np.transpose(arr)
print(t)
f = arr.flatten()
print(f)

[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
# reshape():
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr1 = arr.reshape(2,3) # .shape is a method and .reshape() is a function arr.shape = r,c & arr.reshape(r,c)
print(arr1)

In [15]:
# arrange():
import numpy as np
arr = np.arange(1,10) # accept float as step size !!
ls = arr % 5 # it is easy to perform mathematical operation in ndarray 
print(ls)

[1 2 3 4 0 1 2 3 4]


In [17]:
# sin()
arr = np.arange(10,20)
out = np.sin(arr)
print(out)

[-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
 -0.28790332 -0.96139749 -0.75098725  0.14987721]


In [24]:
num = np.random.randint(1,3)
print(num)

2


In [25]:
arr = np.array([3,65,6,90])
k = arr.max()
print(k)

90


In [18]:
import numpy as np
arr = np.arange(1,13).reshape(4,3)
out = np.sum(arr,0) # axis = 1  (0 is row wise and 1 id column wise)
print(arr)
print(out)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[22 26 30]
